// google-merchant-sync — admin-only edge function that reads the pre-built price book
// (price-book.json, generated by scripts/metro/export-price-book.mjs from src/metro/** +
// src/services/googleShopping/priceBookExport.ts) and upserts it into Google Merchant
// Center via the Merchant API: one `region` per metro delivery zone, one `productInput`
// per (metro, category, variant), and one `regionalInventory` override per (product, zone)
// carrying that zone's real delivered price. See
// docs/metro/research/merchant-api-implementation.md for the full architecture writeup and
// docs/metro/research/ai-ads-and-google-shopping.md (Part B) for why this replaces the
// sunsetting Content API v2.1 integration in src/services/googleShopping/merchantCenter.ts.
//
// Auth: admin-only. Two accepted methods (either is sufficient):
//   1. A Supabase user JWT in `Authorization: Bearer <token>` whose email passes the
//      existing `check_user_admin_status` RPC (same function useAuth.ts/DashboardLayout.tsx
//      use to gate /dashboard) — the normal path from the admin UI.
//   2. A shared secret in the `x-merchant-sync-secret` header, matching the
//      GOOGLE_MERCHANT_SYNC_ADMIN_SECRET env var — for non-interactive callers (a future
//      cron/CLI trigger) that don't hold a user session.
//
// Safety: `dryRun` defaults to true and returns the built payloads without calling Google at
// all. Only an explicit `{"dryRun": false}` body triggers live calls.
import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.45.0';
import { mintGoogleAccessToken, parseServiceAccountJson } from './googleAuth.ts';
import { buildPayloadsForPriceBook, pushAll } from './merchantApi.ts';
import type { PriceBook, SyncSummary } from './types.ts';

// Read (not `import ... with { type: "json" }`) on purpose: JSON import attributes need a
// fairly recent Deno release and this repo's other functions still pin
// deno.land/std@0.168.0, so a plain readTextFile + JSON.parse is the safer, version-agnostic
// choice for a file that's bundled alongside this function either way.
async function loadPriceBook(): Promise<PriceBook> {
  const path = new URL('./price-book.json', import.meta.url);
  const text = await Deno.readTextFile(path);
  return JSON.parse(text) as PriceBook;
}

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type, x-merchant-sync-secret',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
};

const jsonResponse = (body: unknown, status = 200): Response =>
  new Response(JSON.stringify(body), { status, headers: { ...corsHeaders, 'Content-Type': 'application/json' } });

/** Verifies the caller is an admin via the same RPC the dashboard uses, scoped to their own JWT. */
async function isAdminViaUserJwt(authHeader: string, supabaseUrl: string, supabaseAnonKey: string): Promise<boolean> {
  const client = createClient(supabaseUrl, supabaseAnonKey, {
    global: { headers: { Authorization: authHeader } },
  });

  const {
    data: { user },
    error: userError,
  } = await client.auth.getUser();
  if (userError || !user?.email) return false;

  const { data, error } = await client.rpc('check_user_admin_status', { user_email: user.email });
  if (error) return false;
  return data === true;
}

function isAdminViaSharedSecret(req: Request): boolean {
  const expected = Deno.env.get('GOOGLE_MERCHANT_SYNC_ADMIN_SECRET');
  if (!expected) return false;
  const provided = req.headers.get('x-merchant-sync-secret');
  return !!provided && provided === expected;
}

interface SyncRequestBody {
  dryRun?: boolean;
  metroSlug?: string;
}

serve(async req => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { status: 200, headers: corsHeaders });
  }

  if (req.method !== 'POST') {
    return jsonResponse({ error: 'Method not allowed' }, 405);
  }

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL');
    const supabaseAnonKey = Deno.env.get('SUPABASE_ANON_KEY');
    if (!supabaseUrl || !supabaseAnonKey) {
      return jsonResponse({ error: 'Server configuration error (missing Supabase env vars)' }, 500);
    }

    // --- Admin auth ---
    let authorized = isAdminViaSharedSecret(req);
    if (!authorized) {
      const authHeader = req.headers.get('authorization');
      if (authHeader?.startsWith('Bearer ')) {
        authorized = await isAdminViaUserJwt(authHeader, supabaseUrl, supabaseAnonKey);
      }
    }
    if (!authorized) {
      return jsonResponse({ error: 'Admin access required' }, 403);
    }

    // --- Parse request ---
    let body: SyncRequestBody = {};
    try {
      const text = await req.text();
      if (text) body = JSON.parse(text);
    } catch {
      return jsonResponse({ error: 'Invalid JSON body' }, 400);
    }
    const dryRun = body.dryRun !== false; // default true — see file header
    const metroFilter = body.metroSlug ?? null;

    const priceBook = await loadPriceBook();
    if (metroFilter && !priceBook.metros.some(m => m.slug === metroFilter)) {
      return jsonResponse(
        { error: `Unknown metroSlug "${metroFilter}". Known metros: ${priceBook.metros.map(m => m.slug).join(', ')}` },
        400,
      );
    }

    const payloads = buildPayloadsForPriceBook(priceBook, metroFilter);

    const summary: SyncSummary = {
      dryRun,
      metroFilter,
      generatedAt: new Date().toISOString(),
      priceBookGeneratedAt: priceBook.generatedAt,
      counts: {
        regions: payloads.regions.length,
        productInputs: payloads.productInputs.length,
        regionalInventories: payloads.regionalInventories.length,
      },
    };

    if (dryRun) {
      summary.payloads = payloads;
      return jsonResponse(summary);
    }

    // --- Live sync path ---
    const merchantAccountId = Deno.env.get('GOOGLE_MERCHANT_ACCOUNT_ID');
    const serviceAccountRaw = Deno.env.get('GOOGLE_SERVICE_ACCOUNT_JSON');
    const dataSourceId = Deno.env.get('GOOGLE_MERCHANT_DATA_SOURCE_ID') ?? undefined;
    if (!merchantAccountId || !serviceAccountRaw) {
      return jsonResponse(
        { error: 'Server configuration error (missing GOOGLE_MERCHANT_ACCOUNT_ID or GOOGLE_SERVICE_ACCOUNT_JSON)' },
        500,
      );
    }

    let accessToken: string;
    try {
      const serviceAccount = parseServiceAccountJson(serviceAccountRaw);
      accessToken = await mintGoogleAccessToken(serviceAccount);
    } catch (err) {
      console.error('Google auth failed:', err);
      return jsonResponse({ error: `Google auth failed: ${err instanceof Error ? err.message : String(err)}` }, 502);
    }

    const results = await pushAll(payloads, { accessToken, merchantAccountId, dataSourceId });
    summary.results = results;
    // Keep the live-mode response small: don't echo every payload back, only the counts +
    // per-item results (with full detail for failures) computed above.
    return jsonResponse(summary, results.failed > 0 ? 207 : 200);
  } catch (error) {
    console.error('google-merchant-sync error:', error);
    return jsonResponse({ error: 'Internal error', detail: error instanceof Error ? error.message : String(error) }, 500);
  }
});
