// Long Island metro configuration — MGG's pilot metro, fulfilled by a single signed
// partner yard (Eastern Landscape & Mason Supply, Center Moriches). Node prices below
// are 2025–26 medians observed at ELM; treat as reference pricing, not a signed MGG
// price sheet (priceBookConfirmed stays false until that's in place). All categories
// sell by the yard here (unlike DFW, where gravel/sand sell by the ton).

import type { Metro, MetroTown, Truck } from '../types';

const trucks: Truck[] = [
  { id: 'small', name: 'Small dump', capacityTons: 7, capacityYards: 7, deliveryCostFactor: 1 },
  { id: 'medium', name: 'Medium dump', capacityTons: 14, capacityYards: 10, deliveryCostFactor: 1.4 },
  { id: 'large', name: 'Tri-axle', capacityTons: 28, capacityYards: 20, deliveryCostFactor: 2 },
];

const towns: MetroTown[] = [
  {
    slug: 'center-moriches',
    name: 'Center Moriches',
    zoneSlug: 'li-core',
    zip: '11934',
    note: 'Home to the Eastern LM yard — the shortest delivery run on Long Island.',
  },
  {
    slug: 'east-moriches',
    name: 'East Moriches',
    zoneSlug: 'li-core',
    zip: '11940',
    note: 'Core-zone delivery from the Center Moriches yard.',
  },
  {
    slug: 'manorville',
    name: 'Manorville',
    zoneSlug: 'li-core',
    zip: '11949',
    note: 'Core-zone delivery from the Center Moriches yard.',
  },
  {
    slug: 'mastic',
    name: 'Mastic',
    zoneSlug: 'li-core',
    zip: '11950',
    note: 'Core-zone delivery from the Center Moriches yard.',
  },
  {
    slug: 'mastic-beach',
    name: 'Mastic Beach',
    zoneSlug: 'li-core',
    zip: '11951',
    note: 'Core-zone delivery from the Center Moriches yard.',
  },
  {
    slug: 'shirley',
    name: 'Shirley',
    zoneSlug: 'li-core',
    zip: '11967',
    note: 'Core-zone delivery from the Center Moriches yard.',
  },
  {
    slug: 'eastport',
    name: 'Eastport',
    zoneSlug: 'li-core',
    zip: '11941',
    note: 'Core-zone delivery from the Center Moriches yard.',
  },
  {
    slug: 'westhampton-beach',
    name: 'Westhampton Beach',
    zoneSlug: 'li-west-hamptons',
    zip: '11978',
    note: 'West Hamptons zone delivery from the Center Moriches yard.',
  },
  {
    slug: 'quogue',
    name: 'Quogue',
    zoneSlug: 'li-west-hamptons',
    zip: '11959',
    note: 'West Hamptons zone delivery from the Center Moriches yard.',
  },
  {
    slug: 'remsenburg',
    name: 'Remsenburg',
    zoneSlug: 'li-west-hamptons',
    zip: '11960',
    note: 'West Hamptons zone delivery from the Center Moriches yard.',
  },
  {
    slug: 'southampton',
    name: 'Southampton',
    zoneSlug: 'li-east-end',
    zip: '11968',
    note: 'East End zone delivery from the Center Moriches yard.',
  },
  {
    slug: 'hampton-bays',
    name: 'Hampton Bays',
    zoneSlug: 'li-east-end',
    zip: '11946',
    note: 'East End zone delivery from the Center Moriches yard.',
  },
  {
    slug: 'riverhead',
    name: 'Riverhead',
    zoneSlug: 'li-east-end',
    zip: '11901',
    note: 'East End zone delivery from the Center Moriches yard.',
  },
];

export const longIsland: Metro = {
  slug: 'long-island',
  name: 'Long Island',
  shortName: 'Long Island',
  state: 'NY',
  timeZone: 'America/New_York',
  status: 'pilot',
  headline: 'Gravel, mulch, sand & soil — delivered across Long Island',
  subhead: "One delivered price. Pick a day. Fulfilled by Eastern LM in Center Moriches.",
  priceBookConfirmed: false,
  nodes: [
    {
      id: 'eastern-lm',
      name: 'Eastern Landscape & Mason Supply',
      publicLabel: 'Eastern LM yard — Center Moriches',
      cutoffHour: 11,
      deliversSaturday: true,
    },
  ],
  zones: [
    {
      slug: 'li-core',
      name: 'Core (Center Moriches area)',
      loadCost: 35,
      minUnits: 1,
      zips: ['11934', '11940', '11949', '11955', '11950', '11951', '11967', '11941'],
    },
    {
      slug: 'li-west-hamptons',
      name: 'West Hamptons',
      loadCost: 75,
      minUnits: 3,
      zips: ['11960', '11972', '11977', '11978', '11959', '11942'],
    },
    {
      slug: 'li-brookhaven',
      name: 'Brookhaven',
      loadCost: 75,
      minUnits: 3,
      zips: [
        '11772', '11713', '11719', '11980', '11961', '11763',
        '11727', '11742', '11953', '11738', '11720', '11784',
      ],
    },
    {
      slug: 'li-east-end',
      name: 'East End',
      loadCost: 100,
      minUnits: 3,
      zips: [
        '11946', '11968', '11976', '11963', '11932', '11937',
        '11901', '11933', '11947', '11952', '11948', '11956', '11931', '11935',
      ],
    },
    {
      slug: 'li-north-shore',
      name: 'North Shore',
      loadCost: 125,
      minUnits: 5,
      zips: ['11792', '11786', '11778', '11789'],
    },
  ],
  towns,
  categories: [
    {
      slug: 'gravel',
      name: 'Gravel',
      tagline: 'Pea gravel, washed gravel and bluestone for driveways and landscaping',
      unit: 'yd',
      tonsPerYard: 1.4,
      defaultDepthIn: 3,
      variants: [
        {
          slug: 'pea-gravel-38',
          name: '3/8" Pea Gravel',
          shortDescription: 'Small, smooth rounded stone commonly used for walkways, patios and drainage.',
          bestFor: ['Walkways', 'Patios', 'French drains'],
          nodePricePerUnit: 75,
          swatch: '#C7B299',
          popular: true,
        },
        {
          slug: 'washed-gravel-34',
          name: '3/4" Washed Gravel',
          shortDescription: 'Washed, angular 3/4" stone used as a drainage and base material.',
          bestFor: ['Drainage', 'Driveways', 'Base layer'],
          nodePricePerUnit: 75,
          swatch: '#A8A296',
        },
        {
          slug: 'bluestone-34',
          name: '3/4" Bluestone',
          shortDescription: 'Crushed blue-gray traprock in the 3/4" range, a common Long Island driveway stone.',
          bestFor: ['Driveways', 'Parking areas', 'Base layer'],
          nodePricePerUnit: 88,
          swatch: '#5C6670',
          popular: true,
        },
        {
          slug: 'bluestone-38',
          name: '3/8" Bluestone',
          shortDescription: 'Crushed blue-gray traprock in a finer 3/8" size for a tighter walking surface.',
          bestFor: ['Walkways', 'Patios', 'Fine driveway topping'],
          nodePricePerUnit: 88,
          swatch: '#6B7580',
        },
        {
          slug: 'whitestone-34',
          name: '3/4" Whitestone',
          shortDescription: 'Crushed light-colored stone in the 3/4" range used as a decorative driveway topping.',
          bestFor: ['Driveways', 'Decorative landscaping', 'Parking areas'],
          nodePricePerUnit: 125,
          swatch: '#D8D5CC',
        },
        {
          slug: 'rca-state',
          name: 'State-Grade RCA (driveway base)',
          shortDescription: 'Recycled concrete aggregate meeting NYSDOT base specifications.',
          bestFor: ['Driveway base', 'Road base', 'Compacted surfaces'],
          nodePricePerUnit: 27,
          swatch: '#9C9A94',
        },
      ],
    },
    {
      slug: 'sand',
      name: 'Sand',
      tagline: 'Fine and concrete sand for masonry, fill and play areas',
      unit: 'yd',
      tonsPerYard: 1.35,
      defaultDepthIn: 2,
      variants: [
        {
          slug: 'fine-sand',
          name: 'Fine Sand',
          shortDescription: 'Fine-graded sand used for leveling, play areas and light fill.',
          bestFor: ['Paver leveling', 'Play areas', 'Fill'],
          nodePricePerUnit: 50,
          swatch: '#E3D3AC',
          popular: true,
        },
        {
          slug: 'concrete-sand',
          name: 'State Concrete Sand',
          shortDescription: 'Coarse, NYSDOT-spec concrete sand used as a mixing and bedding sand.',
          bestFor: ['Concrete mix', 'Paver base', 'Pipe bedding'],
          nodePricePerUnit: 50,
          swatch: '#D9C8A6',
        },
      ],
    },
    {
      slug: 'mulch',
      name: 'Mulch',
      tagline: 'Dyed and natural mulch for garden beds and landscaping',
      unit: 'yd',
      tonsPerYard: 0.3,
      defaultDepthIn: 3,
      variants: [
        {
          slug: 'black-mulch',
          name: 'Black Mulch',
          shortDescription: 'Hardwood mulch dyed black for a dark, uniform bed color that holds through the season.',
          bestFor: ['Garden beds', 'Foundation plantings', 'High-contrast borders'],
          nodePricePerUnit: 30,
          swatch: '#2B2724',
          popular: true,
        },
        {
          slug: 'dark-natural-mulch',
          name: 'Dark Natural Mulch',
          shortDescription: 'Un-dyed shredded hardwood mulch that weathers to a dark natural brown.',
          bestFor: ['Garden beds', 'Tree rings', 'General landscaping'],
          nodePricePerUnit: 19,
          swatch: '#5A4630',
        },
        {
          slug: 'chocolate-mulch',
          name: 'Chocolate Mulch',
          shortDescription: 'Hardwood mulch dyed a deep chocolate brown for a rich, natural-looking bed color.',
          bestFor: ['Garden beds', 'Foundation plantings', 'Walkway borders'],
          nodePricePerUnit: 30,
          swatch: '#4A3524',
        },
        {
          slug: 'red-mulch',
          name: 'Red Mulch',
          shortDescription: 'Hardwood mulch dyed red for a bold bed color that holds through the season.',
          bestFor: ['Garden beds', 'Foundation plantings', 'Accent borders'],
          nodePricePerUnit: 35,
          swatch: '#7A2E1E',
        },
      ],
    },
    {
      slug: 'soil',
      name: 'Soil',
      tagline: 'Screened topsoil, compost and clean fill for planting and grading',
      unit: 'yd',
      tonsPerYard: 1.1,
      defaultDepthIn: 4,
      variants: [
        {
          slug: 'screened-topsoil',
          name: 'Screened Organic Topsoil',
          shortDescription: 'Screened topsoil with organic content, suited for new lawns and general planting.',
          bestFor: ['New lawns', 'Grading', 'General planting'],
          nodePricePerUnit: 24,
          swatch: '#5B4A38',
          popular: true,
        },
        {
          slug: 'compost',
          name: 'Certified Organic Compost',
          shortDescription: 'Certified organic compost used to amend and enrich existing soil.',
          bestFor: ['Soil amendment', 'Topdressing', 'Garden beds'],
          nodePricePerUnit: 32,
          swatch: '#3A2E22',
        },
        {
          slug: 'clean-fill',
          name: 'Clean Fill',
          shortDescription: 'Clean, low-organic fill dirt used to raise or level grade.',
          bestFor: ['Grading', 'Fill', 'Low spots'],
          nodePricePerUnit: 12,
          swatch: '#6E5A44',
        },
      ],
    },
  ],
  trucks,
  pricing: {
    premiumRate: 0.25,
    additionalLoadDiscount: 0.25,
    saturdayFeeRate: 0.15,
    rushFeeRate: 0.15,
    roundTo: 5,
  },
  phone: '(844) 624-0400',
  phoneHref: 'tel:+18446240400',
};
