
project_id = "losrkjvrcambvgijfism"

[functions.create-payment]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.send-order-sms]
verify_jwt = false

[functions.receive-sms-webhook]
verify_jwt = false

[functions.get-messages]
verify_jwt = true

[functions.mark-messages-read]
verify_jwt = true

[functions.verify-payment]
verify_jwt = false

[functions.voice-response]
verify_jwt = false
