// AUTO-GENERATED by scripts/checkout/export-checkout-v2-bundle.mjs — DO NOT EDIT BY HAND.
// Type declarations for checkout-v2.bundle.js. Real tsc --emitDeclarationOnly output for each
// module src/services/checkoutV2/bundleEntry.ts re-exports (tsc-verified, not hand-duplicated),
// inlined in dependency order with intra-package imports stripped (see DTS_MODULES in
// scripts/checkout/export-checkout-v2-bundle.mjs).
// Regenerate: node scripts/checkout/export-checkout-v2-bundle.mjs
// Generated: 2026-09-29T00:20:43.454Z

// ─── from src/services/checkoutV2/contract.ts ───
export interface StripeItemInput {
    id: string | number;
    name: string;
    description?: string;
    price: number;
    quantity: number;
    image?: string;
    metadata?: Record<string, string | undefined>;
}
export interface CreateAuthHoldV2Request {
    items: StripeItemInput[];
    orderId?: string;
    depositOption?: boolean;
    cancelUrl?: string;
}
export type PriceCheckVerdict = 'ok' | 'mismatch' | 'unverifiable';
/** One item's canonical DB price, as looked up by create-auth-hold-v2 (products.id -> price). */
export interface ProductPriceLookup {
    id: string;
    price: number | null;
}
export interface ItemPriceEvaluation {
    id: string;
    submittedPrice: number;
    dbPrice: number | null;
    verdict: PriceCheckVerdict;
    reason: string;
}
export interface PriceEvaluationResult {
    verdict: PriceCheckVerdict;
    items: ItemPriceEvaluation[];
}
/** Everything create-auth-hold-v2 needs to write into Stripe Checkout Session metadata so
 * verify-payment-v2 can bind the paid session back to the order it was created for (fixes F1)
 * without trusting anything the client resubmits at verification time. */
export interface CheckoutV2Metadata {
    source: 'checkout-v2';
    orderId: string;
    expectedTotalCents: string;
    depositOption: 'true' | 'false';
    priceCheck: PriceCheckVerdict;
    itemsHash: string;
    userId: string;
    userEmail: string;
    isGuest: 'true' | 'false';
}
export declare const CHECKOUT_V2_METADATA_KEYS: (keyof CheckoutV2Metadata)[];
/** Amount-binding tolerance in cents — covers only genuine floating point noise, never a real
 * price difference (a single cent of drift between two independent dollar->cents roundings). */
export declare const AMOUNT_TOLERANCE_CENTS = 1;
/** An item's submitted per-unit price must be at least this fraction of the DB's canonical
 * products.price to be accepted. See pricing.ts's module doc for the full rationale — in short,
 * legitimate discounts observed in this codebase (src/components/cart/CouponCode.tsx) top out
 * at 10%, so 0.5 leaves generous headroom for coupons plus any zip-based surcharge/discount this
 * agent could not find a server-reproducible source of truth for, while still catching the named
 * threat (a tampered client submitting a near-zero price for an expensive order). */
export declare const PRICE_FLOOR_RATIO = 0.5;
export interface BackupCustomerInfo {
    email?: string;
    name?: string;
}
export interface BackupCouponInfo {
    code: string;
    discount: number;
    applied: boolean;
}
export interface BackupUtmData {
    gclid?: string;
    gbraid?: string;
    wbraid?: string;
    utm_source?: string;
    utm_medium?: string;
    utm_campaign?: string;
    utm_term?: string;
    utm_content?: string;
    landing_page_url?: string;
    referrer?: string;
    user_agent?: string;
}
/** Mirrors src/utils/paymentUtils.ts's OrderItemData / CheckoutBackup shape — the localStorage
 * "checkout-order-backup" blob the client sends verify-payment(-v2) as `backupData`. */
export interface BackupItem {
    id: string | number;
    name?: string;
    price: number;
    quantity: number;
    tons?: number;
    deliveryDate?: string | Date;
    deliveryAddress?: {
        street?: string;
        city?: string;
        state?: string;
        zip?: string;
    };
    contactInfo?: {
        name?: string;
        email?: string;
        phone?: string;
    };
    deliveryTimePreference?: string;
    deliveryInstructions?: string;
    total_price?: number;
}
export interface CheckoutBackupV2 {
    orderId: string;
    items: BackupItem[];
    total?: number;
    customerInfo?: BackupCustomerInfo;
    couponInfo?: BackupCouponInfo | null;
    depositOption?: boolean;
    utmData?: BackupUtmData | null;
}
export type OrderStatus = 'pending' | 'authorized' | 'paid' | 'processed' | 'Deposit Paid' | 'review_required';
export interface VerificationInfo {
    paymentVerified: boolean;
    isAuthorized: boolean;
    usedFallback: boolean;
}
/** One row shaped for `orders` Insert — a subset of the generated Database['public']['Tables']
 * ['orders']['Insert'] type (kept local/untyped-against-Database here so this module has zero
 * Deno/supabase-js import surface; the edge function's caller is responsible for the DB write
 * itself and can widen this to the full Insert type there). */
export interface OrderInsertRecord {
    order_id: string;
    stripe_payment_intent_id: string | null;
    stripe_session_id: string | null;
    product_id: string;
    unit: string;
    unit_price: number;
    total_price: number;
    quantity: number;
    status: string;
    delivery_date: string | null;
    delivery_street: string | null;
    delivery_city: string | null;
    delivery_state: string | null;
    delivery_zip: string | null;
    delivery_name: string | null;
    delivery_phone: string | null;
    delivery_email: string | null;
    delivery_time_preference: string | null;
    delivery_instructions: string | null;
    billing_name: string | null;
    billing_email: string | null;
    coupon: string | null;
    is_deposit_payment: boolean;
    deposit_amount: number | null;
    balance_due: number | null;
    gclid: string | null;
    gbraid: string | null;
    wbraid: string | null;
    utm_source: string | null;
    utm_medium: string | null;
    utm_campaign: string | null;
    utm_term: string | null;
    utm_content: string | null;
    landing_page_url: string | null;
    referrer: string | null;
    user_agent: string | null;
}

// ─── from src/services/checkoutV2/pricing.ts ───
export declare const DEPOSIT_AMOUNT_CENTS = 19900;
/** Cents Stripe will actually charge for one line item — matches create-auth-hold's
 * `unit_amount: Math.round(item.price * 100)` times Stripe's own quantity multiplication. Using
 * this (not a single round-the-grand-total operation) keeps the expected total exactly equal to
 * what Stripe will report back as `amount_total`, cent for cent. */
export declare const lineItemAmountCents: (item: Pick<StripeItemInput, "price" | "quantity">) => number;
export declare const computeBaseAmountCents: (items: Pick<StripeItemInput, "price" | "quantity">[]) => number;
export declare const computeExpectedTotalCents: (items: Pick<StripeItemInput, "price" | "quantity">[], depositOption: boolean | undefined) => number;
/** amount_total (from Stripe, cents) vs. expectedTotalCents (from our own metadata). */
export declare const amountsMatch: (actualCents: number | null | undefined, expectedCents: number, toleranceCents?: number) => boolean;
/** Evaluates every item's submitted price against its DB price. Deposit checkouts are always
 * 'ok' (see module doc) — the per-item comparison is skipped entirely for them since the $199
 * flat fee has nothing to do with individual item prices. */
export declare const evaluateItemPrices: (items: StripeItemInput[], dbPrices: ProductPriceLookup[], depositOption: boolean | undefined) => PriceEvaluationResult;
/** Coupon + deposit math ported faithfully from verify-payment/index.ts's fresh-insert branch
 * (lines ~608-688) so verify-payment-v2 computes identical per-item total_price/deposit_amount/
 * balance_due values. `items` here are the *backup* items (post add-to-cart, pre-Stripe), each
 * carrying its own `total_price` (== price * quantity, before any coupon discount). */
export interface DepositCouponInput {
    items: {
        total_price: number;
    }[];
    couponDiscount: number;
    depositOption: boolean;
}
export interface DepositCouponItemResult {
    finalItemPrice: number;
    depositAmount: number | null;
    balanceDue: number | null;
}
export declare const computeItemFinalPricing: (input: DepositCouponInput) => DepositCouponItemResult[];

// ─── from src/services/checkoutV2/metadata.ts ───
/** A short, non-cryptographic order-contents fingerprint — purely a diagnostic breadcrumb (does
 * this verified session's line items look like the same cart the client most recently held in
 * `backupData`?), never used as a security boundary by itself (amount + orderId binding are).
 * FNV-1a keeps this dependency-free and stable across the Deno bundle / browser / vitest. */
export declare const hashItems: (items: Pick<StripeItemInput, "id" | "price" | "quantity">[]) => string;
export interface BuildMetadataInput {
    orderId: string;
    expectedTotalCents: number;
    depositOption: boolean;
    priceCheck: PriceCheckVerdict;
    items: Pick<StripeItemInput, 'id' | 'price' | 'quantity'>[];
    userId: string;
    userEmail: string;
    isGuest: boolean;
}
export declare const buildCheckoutV2Metadata: (input: BuildMetadataInput) => CheckoutV2Metadata;
export type ParsedCheckoutV2Metadata = {
    ok: true;
    data: CheckoutV2Metadata;
} | {
    ok: false;
    error: string;
};
/** Returns ok:false (never throws) whenever the metadata doesn't look like it was written by
 * create-auth-hold-v2 — this is the signal verify-payment-v2 uses to tell "a real checkout-v2
 * session" apart from sessions created by other, un-migrated entry points (create-quote-checkout,
 * the landing page's create-payment) so it can fall back to looser handling for those instead of
 * wrongly flagging every non-v2 session as tampered. See live-checkout-v2.md's "v1 -> v2 behavior
 * differences" section. */
export declare const parseCheckoutV2Metadata: (metadata: Record<string, string | null | undefined> | null | undefined) => ParsedCheckoutV2Metadata;
export declare const metadataKeyCount: number;

// ─── from src/services/checkoutV2/binding.ts ───
export type SessionOrigin = {
    kind: 'checkout-v2';
    metadata: CheckoutV2Metadata;
} | {
    kind: 'quote-conversion';
    quoteId: string;
} | {
    kind: 'unrecognized';
};
/** verify-payment-v2 receives requests originating from three different, independently-created
 * Stripe sessions: (1) create-auth-hold-v2 (this agent's new function — full binding below), (2)
 * create-quote-checkout (existing, unmodified — metadata `{quote_id, type: "quote_conversion"}`;
 * bound separately in orderRecords.ts against the DB's own stored quote total, which IS a
 * reliable source of truth unlike cart pricing), (3) anything else, chiefly the landing page's
 * `create-payment` function, which is out of this agent's ownership and unmodified. Case (3)
 * cannot be bound at all — verify-payment-v2 documents this gap in live-checkout-v2.md rather
 * than silently mis-flagging every landing-page order as tampered. */
export declare const classifySessionOrigin: (metadata: Record<string, string | null | undefined> | null | undefined) => SessionOrigin;
export interface BindingResult {
    ok: boolean;
    reason?: string;
}
/** Requested orderId (from the client's verify-payment-v2 call) must equal the orderId the
 * session was actually created for. Both QUOTE- and its ORDER- converted form are accepted since
 * PaymentSuccess.tsx sends whichever it has (quote_id param converts QUOTE- -> ORDER- client
 * side before calling verify-payment-v2 in some code paths — see PaymentSuccess.tsx's
 * `finalOrderId` derivation). */
export declare const checkOrderIdBinding: (sessionOrderId: string, requestedOrderId: string | undefined | null) => BindingResult;
export declare const checkAmountBinding: (actualAmountTotalCents: number | null | undefined, expectedTotalCents: number) => BindingResult;
/** Combines both checks — first failure short-circuits (order id is checked first since an
 * amount mismatch is meaningless context if the order id itself is wrong). */
export declare const evaluateBinding: (sessionOrderId: string, requestedOrderId: string | undefined | null, actualAmountTotalCents: number | null | undefined, expectedTotalCents: number) => BindingResult;

// ─── from src/services/checkoutV2/statusMapping.ts ───
export declare const computeOrderStatus: (verification: VerificationInfo, isDepositPayment: boolean) => OrderStatus;
/** Wraps computeOrderStatus for the review_required override — used whenever binding
 * (src/services/checkoutV2/binding.ts) fails or the price-floor check rejected the order at
 * create time but a real payment still landed (see live-checkout-v2.md: "never silently drop a
 * paid order"). */
export declare const computeOrderStatusWithReview: (verification: VerificationInfo, isDepositPayment: boolean, reviewRequired: boolean) => OrderStatus;

// ─── from src/services/checkoutV2/idempotency.ts ───
export interface ExistingOrderRowLike {
    id: string;
    stripe_session_id?: string | null;
}
export interface IdempotencyDecision {
    alreadyProcessed: boolean;
    rows: ExistingOrderRowLike[];
}
export declare const decideIdempotency: (existingRows: ExistingOrderRowLike[] | null | undefined) => IdempotencyDecision;

// ─── from src/services/checkoutV2/emailPayload.ts ───
export declare const escapeHtml: (input: string | null | undefined) => string;
export interface EmailOrderRow {
    product_name: string;
    quantity: number;
    total_price: number;
    delivery_date?: string | null;
    delivery_street?: string | null;
    delivery_city?: string | null;
    delivery_state?: string | null;
    delivery_zip?: string | null;
    delivery_name?: string | null;
    delivery_email?: string | null;
    delivery_phone?: string | null;
    delivery_time_preference?: string | null;
    delivery_instructions?: string | null;
}
export interface EmailOrderItem {
    product_name: string;
    quantity: number;
    total_price: number;
    delivery_date?: string;
    delivery_address?: {
        street: string;
        city: string;
        state: string;
        zip: string;
    };
    contact_info?: {
        name: string;
        email: string;
        phone: string;
    };
    delivery_time_preference?: string;
    delivery_instructions?: string;
}
export interface EmailOrderData {
    order_id: string;
    items: EmailOrderItem[];
    total_amount: number;
    customer_email: string;
    customer_name: string;
    base_total?: number;
    coupon_info?: {
        code: string;
        total_discount: number;
        applied: boolean;
    } | null;
    is_deposit_payment?: boolean;
    deposit_amount?: number;
    balance_due?: number;
}
export interface BuildOrderEmailDataInput {
    orderId: string;
    rows: EmailOrderRow[];
    customerEmail: string;
    customerName: string;
    couponInfo?: {
        code: string;
        discount: number;
    } | null;
    baseTotal?: number;
    isDepositPayment?: boolean;
    depositAmount?: number | null;
    balanceDue?: number | null;
}
/** Builds the exact object shape src/utils/emailTemplates.ts's generateCustomerConfirmationEmail
 * / generateInternalNotificationEmail expect (their local, unexported `OrderData` interface —
 * matched structurally here rather than imported, since it isn't exported), with every
 * user-controlled string field escaped. */
export declare const buildOrderEmailData: (input: BuildOrderEmailDataInput) => EmailOrderData;
export declare const buildCustomerEmailSubject: (orderId: string) => string;
export declare const buildInternalEmailSubject: (customerName: string) => string;
/** review_required internal alert — a distinct email from the normal internal notification,
 * sent when a binding check (src/services/checkoutV2/binding.ts) or the price floor
 * (src/services/checkoutV2/pricing.ts) fails but a real Stripe payment still exists, so a human
 * has to look at it (requirement (b): "never silently drop a paid order"). */
export declare const buildReviewRequiredAlertSubject: (orderId: string) => string;
export declare const buildReviewRequiredAlertHtml: (opts: {
    orderId: string;
    reason: string;
    sessionId: string | null;
}) => string;

// ─── from src/services/checkoutV2/orderRecords.ts ───
export interface BuildFreshOrderRecordsInput {
    orderId: string;
    items: BackupItem[];
    status: OrderStatus;
    stripeSessionId: string | null;
    stripePaymentIntentId: string | null;
    billingName: string;
    billingEmail: string;
    couponCode: string | null;
    couponDiscount: number;
    depositOption: boolean;
    utmData?: BackupUtmData | null;
}
export declare const buildFreshOrderRecords: (input: BuildFreshOrderRecordsInput) => OrderInsertRecord[];
export interface QuoteConversionUpdateInput {
    orderIdFromQuote: string;
    status: OrderStatus;
    stripeSessionId: string | null;
    stripePaymentIntentId: string | null;
    utmData?: BackupUtmData | null;
}
/** Update payload for flipping existing `status = 'Quote'` rows (matched by the original
 * `QUOTE-...` order_id) to a confirmed order — mirrors verify-payment/index.ts lines 412-436. */
export declare const buildQuoteConversionUpdate: (input: QuoteConversionUpdateInput) => {
    gclid: string;
    gbraid: string;
    wbraid: string;
    utm_source: string;
    utm_medium: string;
    utm_campaign: string;
    utm_term: string;
    utm_content: string;
    landing_page_url: string;
    referrer: string;
    user_agent: string;
    order_id: string;
    status: OrderStatus;
    stripe_payment_intent_id: string;
    stripe_session_id: string;
    quote_converted: boolean;
};

// ─── from src/utils/emailTemplates.ts ───
interface OrderItem {
    product_name: string;
    quantity: number;
    total_price: number;
    delivery_date?: string;
    delivery_address?: {
        street: string;
        city: string;
        state: string;
        zip: string;
    };
    contact_info?: {
        name: string;
        email: string;
        phone: string;
    };
    delivery_time_preference?: string;
    delivery_instructions?: string;
}
interface OrderData {
    order_id: string;
    items: OrderItem[];
    total_amount: number;
    customer_email: string;
    customer_name?: string;
    base_total?: number;
    coupon_info?: {
        code: string;
        total_discount: number;
        applied: boolean;
    } | null;
    is_deposit_payment?: boolean;
    deposit_amount?: number;
    balance_due?: number;
}
export declare const generateCustomerConfirmationEmail: (orderData: OrderData) => string;
export declare const generateInternalNotificationEmail: (orderData: OrderData) => string;
interface CartSaveEmailItem {
    product_name: string;
    quantity: number;
    total_price: number;
    delivery_date?: string;
    delivery_address?: {
        street: string;
        city: string;
        state: string;
        zip: string;
    } | null;
    delivery_time_preference?: string;
}
interface CartSaveEmailData {
    customer_name: string;
    order_id: string;
    items: CartSaveEmailItem[];
    total_amount: number;
}
export declare const generateCartSaveCustomerEmail: (data: CartSaveEmailData) => string;
export {};
