// AUTO-GENERATED by scripts/metro/export-metro-checkout-bundle.mjs — DO NOT EDIT BY HAND.
// Type declarations for metro-checkout.bundle.js (G2, docs/metro/research/metro-checkout-rereview.md).
// Real tsc --emitDeclarationOnly output for src/metro/checkout/bundleEntry.ts's dependency graph
// (tsc-verified, not hand-duplicated), scoped to only the names _shared/metro-conversion-runner.ts
// (and any other edge function) actually type-imports from the bundle today. See
// scripts/metro/export-metro-checkout-bundle.mjs's DTS_WHOLE_FILE_INCLUDES/DTS_CHERRY_PICKS for
// exactly what's included and why.
// Regenerate: node scripts/metro/export-metro-checkout-bundle.mjs
// Generated: 2026-09-29T00:28:52.471Z

// ─── from src/metro/checkout/contract.ts (included in full — self-contained) ───
export declare const METRO_CHECKOUT_FUNCTION = "create-metro-checkout";
/** No more CART- staging prefix — the order id is generated once, at checkout-session-creation
 * time, and is never renamed. Old CART-METRO- rows (if any exist from before this change shipped)
 * are not migrated; they age out via the existing abandoned-cart flow like any other cart. */
export declare const METRO_ORDER_ID_PREFIX = "ORDER-METRO-";
/** Max allowed |client expectedTotal − server total| in dollars before PRICE_CHANGED. */
export declare const METRO_PRICE_TOLERANCE = 0.01;
export declare const METRO_VERIFY_FUNCTION = "verify-metro-payment";
export declare const METRO_CONFIRMATION_PATH = "/metro-order-confirmed";
export declare const METRO_INPUT_CAPS: {
    readonly name: 100;
    readonly email: 254;
    readonly mobile: 20;
    readonly street: 200;
    readonly city: 100;
    readonly state: 2;
    readonly zip: 5;
    readonly dropNotes: 500;
    readonly utmValue: 200;
    readonly maxUtmKeys: 10;
};
/** Quantity cap — largest configured truck capacity across both metros today is 28 tons /
 * 20 cubic yards (Long Island's tri-axle); ×10 headroom would be 280. Rounded up to a flat 500
 * (units are tons or cubic yards depending on category) so the cap is easy to remember and state
 * to a customer, while still being far below anything that would make `planLoads`' truck-splitting
 * loop (src/metro/lib/pricing.ts) do meaningful work — closes security-review F6 (quantity-DoS). */
export declare const METRO_QUANTITY_MAX = 500;
/** Half-unit step, matching the client UI's own rounding (`roundToHalf` in useMetroOrder.ts) —
 * enforced server-side too so a bypassed/tampered client can't submit e.g. 7.3333 units
 * (security-review F9). */
export declare const METRO_QUANTITY_STEP = 0.5;
/** Allowlist of tracking/attribution keys accepted from the client's `utmData` object — exactly
 * 10, matching METRO_INPUT_CAPS.maxUtmKeys, so "every allowlisted key" and "the cap" are the same
 * number by construction. `user_agent` is deliberately NOT in this list: create-metro-checkout
 * captures the real `User-Agent` request header server-side instead of trusting a client-supplied
 * value for it (see create-metro-checkout/index.ts). */
export declare const ALLOWED_UTM_KEYS: readonly ["gclid", "gbraid", "wbraid", "utm_source", "utm_medium", "utm_campaign", "utm_term", "utm_content", "landing_page_url", "referrer"];
export type AllowedUtmKey = (typeof ALLOWED_UTM_KEYS)[number];
export declare const METRO_CHECKOUT_METADATA_KEYS: readonly ["source", "orderId", "metroSlug", "zip", "categorySlug", "variantSlug", "quantity", "deliveryDate", "zoneSlug", "name", "mobile", "street", "city", "state", "dropNotes", "serverTotal", "expectedTotal", "userId", "userEmail", "isGuest", "depositOption", "fullOrderAmount", "gclid", "gbraid", "wbraid", "utm_source", "utm_medium", "utm_campaign", "utm_term", "utm_content", "landing_page_url", "referrer", "user_agent"];
export interface MetroVerifyRequest {
    sessionId: string;
    orderId: string;
}
/** Display-ready fields for the /metro-order-confirmed page. */
export interface MetroConfirmedOrder {
    orderId: string;
    metroSlug: string;
    variantName: string;
    quantity: number;
    unit: 'ton' | 'yd';
    total: number;
    deliveryDate: string;
    deliveryStreet: string;
    deliveryCity?: string;
    deliveryState: string;
    deliveryZip: string;
    zoneName?: string;
    truckPlan?: string;
    customerEmail: string;
    /** Additive (G3, docs/metro/research/metro-checkout-rereview.md) — the paying customer's own
     * name/phone, fed to Google Ads Enhanced Conversions by metroPurchaseTracking.ts. Safe to
     * return here: this whole response is already gated behind knowing the order's Stripe
     * `session_id` (see verifyLogic.ts's validateSession), the same trust boundary that already
     * guards `customerEmail`/the delivery address above. */
    customerName?: string;
    customerPhone?: string;
}
export type MetroVerifyResponse = {
    success: true;
    orderId: string;
    /** 'test' — Stripe TEST-mode checkout (staging origin; session.livemode === false), never a
     * real charge. See docs/metro/research/metro-checkout-server.md "Staging / test mode". */
    status: 'authorized' | 'paid' | 'test';
    alreadyProcessed: boolean;
    order: MetroConfirmedOrder;
} | {
    success: false;
    status: 'unpaid' | 'invalid' | 'mismatch' | 'not_found' | 'error';
    error: string;
};
export interface MetroCheckoutRequest {
    metroSlug: string;
    zip: string;
    categorySlug: string;
    variantSlug: string;
    /** In the category's sell unit (ton | yd). */
    quantity: number;
    /** YYYY-MM-DD; must be one of getDeliveryDayOptions(metro, now) on the server. */
    deliveryDate: string;
    contact: {
        name: string;
        email: string;
        mobile: string;
    };
    address: {
        street: string;
        city?: string;
        state: string;
        zip: string;
    };
    dropNotes?: string;
    /** Client-displayed total in dollars; server rejects with PRICE_CHANGED if it differs. */
    expectedTotal: number;
    utmData?: Record<string, string>;
    /** Path (must start with '/') to return to if the customer cancels in Stripe. */
    cancelPath?: string;
}
/** Server-authoritative quote echoed back to the client (dollars). */
export interface MetroServerQuote {
    metroSlug: string;
    zoneSlug: string;
    zoneName: string;
    categorySlug: string;
    variantSlug: string;
    variantName: string;
    unit: 'ton' | 'yd';
    quantity: number;
    deliveryDate: string;
    isSaturday: boolean;
    isRush: boolean;
    truckPlan: string;
    basePrice: number;
    saturdayFee: number;
    rushFee: number;
    total: number;
    pricePerUnit: number;
}
export interface MetroCheckoutSuccess {
    url: string;
    session_id: string;
    order_id: string;
    serverQuote: MetroServerQuote;
}
export type MetroCheckoutErrorCode = 'INVALID_INPUT' | 'PRICE_BOOK_UNCONFIRMED' | 'OUT_OF_AREA' | 'DATE_UNAVAILABLE' | 'BELOW_MINIMUM' | 'PRICE_CHANGED' | 'SERVER_ERROR';
export interface MetroCheckoutError {
    error: string;
    code: MetroCheckoutErrorCode;
    serverQuote?: MetroServerQuote;
}
export type MetroCheckoutResponse = MetroCheckoutSuccess | MetroCheckoutError;

// ─── from src/metro/checkout/emailTemplates.ts (included in full — self-contained) ───
/** Escapes the five HTML-significant characters. Non-string input is coerced via String() first
 * (so a number/undefined/null can be passed directly without the caller needing a ternary at
 * every call site) — null/undefined become ''. */
export declare const escapeHtml: (value: unknown) => string;
export interface MetroOrderEmailData {
    orderId: string;
    customerName: string;
    customerEmail: string;
    variantName: string;
    quantity: number;
    unit: string;
    totalAmount: number;
    deliveryDate?: string | null;
    deliveryStreet?: string | null;
    deliveryCity?: string | null;
    deliveryState?: string | null;
    deliveryZip?: string | null;
}
export declare const buildCustomerConfirmationHtml: (data: MetroOrderEmailData) => string;
export declare const buildInternalNotificationHtml: (data: MetroOrderEmailData) => string;
/** Internal-only alert for a `review_required` conversion (metadata/price mismatch at verify
 * time) — never sent to the customer; `reason` is our own server-generated diagnostic string
 * (not user input) but is escaped anyway for consistency/defense in depth. */
export declare const buildReviewRequiredInternalHtml: (data: MetroOrderEmailData, reason: string) => string;
/** Data available for the G1 (metro-checkout-rereview.md) order-insert-failure alert — deliberately
 * NOT `MetroOrderEmailData`-shaped: a genuine `orders` insert failure (Postgres outage, etc.) means
 * there is no order row to read customer/material details off of, only what's recoverable from the
 * verified Stripe session itself (metadata + amount) plus the DB error text. */
export interface MetroOrderErrorAlertData {
    orderId: string;
    stripeSessionId: string;
    stripePaymentIntentId: string | null;
    /** Dollars, or null when the session had no resolvable `amount_total`. */
    amount: number | null;
    customerEmail: string;
    dbErrorMessage: string;
}
/** Internal-only alert for a genuine (non-unique-violation) `orders` insert failure after a
 * Stripe payment has already been verified/authorized — see G1 in
 * docs/metro/research/metro-checkout-rereview.md. Reuses the same visual template/escaping
 * approach as `buildReviewRequiredInternalHtml` (never sent to the customer); `dbErrorMessage`
 * is a Postgres/Supabase error string, not user input, but is escaped anyway for defense in
 * depth, same rationale as `reason` above. */
export declare const buildOrderInsertFailedInternalHtml: (data: MetroOrderErrorAlertData) => string;

// ─── MinimalStripeSession, from src/metro/checkout/verifyLogic.ts (cherry-picked) ───
export interface MinimalStripeSession {
    metadata?: Record<string, string | null | undefined> | null;
    amount_total?: number | null;
    payment_intent?: {
        id?: string | null;
        status?: string | null;
    } | string | null;
    created?: number | null;
    /** Stripe's own live/test signal for this session — undefined only for a caller that never set
     * it (e.g. a hand-built test fixture); staging/test-mode conversion handling
     * (metro-conversion-runner.ts) treats that as live, same as `livemode !== false`. */
    livemode?: boolean | null;
}

// ─── ParsedMetroCheckout, from src/metro/checkout/conversion.ts (cherry-picked) ───
export interface ParsedMetroCheckout {
    orderId: string;
    request: MetroCheckoutRequest;
    zoneSlug: string;
    serverTotal: number;
    userId: string;
    userEmail: string;
    isGuest: boolean;
}
