import { METROS } from '@/metro/config';
import { formatUnit } from '@/metro/lib/pricing';
import { formatMoney } from '@/metro/components/shared/priceHelpers';
import {
  estimateDrivewayCost,
  REFERENCE_DRIVEWAY_SQFT,
  REFERENCE_DRIVEWAY_DEPTH_IN,
} from '@/content/guides/drivewayEstimate';

/** One representative top-layer driveway stone per metro, used only for this worked
 * example table — the best-gravel guide covers the full material comparison. */
const EXAMPLE_VARIANT_BY_METRO: Record<string, string> = {
  'dallas-fort-worth': '57-limestone',
  'long-island': 'bluestone-34',
};

/** Live delivered-price table for a common 12x50 ft driveway, computed at render time
 * from the current metro price books — never a hardcoded dollar figure. Pass
 * `metroSlugs` to narrow the table to a single metro (e.g. the DFW guide). */
export function DrivewayCostTable({ metroSlugs }: { metroSlugs?: string[] } = {}) {
  const metros = metroSlugs ? METROS.filter(metro => metroSlugs.includes(metro.slug)) : METROS;
  const rows = metros.map(metro => {
    const variantSlug = EXAMPLE_VARIANT_BY_METRO[metro.slug];
    if (!variantSlug) return null;
    return estimateDrivewayCost(metro, 'gravel', variantSlug);
  }).filter((row): row is NonNullable<typeof row> => row !== null);

  if (rows.length === 0) return null;

  return (
    <div className="overflow-hidden rounded-xl border border-black/10 bg-white">
      <div className="border-b border-black/10 bg-[#F2F1EA] px-4 py-3">
        <p className="text-sm font-bold text-[#0F1115]">
          Example: {REFERENCE_DRIVEWAY_SQFT} sq ft driveway (12 x 50 ft) at {REFERENCE_DRIVEWAY_DEPTH_IN}&quot; deep
        </p>
        <p className="text-xs text-[#0F1115]/60">Delivered price, cheapest zone in each metro</p>
      </div>
      <div className="overflow-x-auto">
        <table className="w-full text-sm">
          <thead>
            <tr className="text-left text-[#0F1115]/50">
              <th className="px-4 py-2 font-medium">Metro</th>
              <th className="px-4 py-2 font-medium">Material</th>
              <th className="px-4 py-2 font-medium">Quantity</th>
              <th className="px-4 py-2 font-medium">Per unit</th>
              <th className="px-4 py-2 font-medium">Delivered total</th>
            </tr>
          </thead>
          <tbody>
            {rows.map(row => (
              <tr key={row.metroSlug} className="border-t border-black/5">
                <td className="px-4 py-3 font-semibold text-[#0F1115]">{row.metroName}</td>
                <td className="px-4 py-3 text-[#0F1115]/70">{row.variantName}</td>
                <td className="px-4 py-3 text-[#0F1115]/70">
                  {row.quantity} {formatUnit(row.unit, row.quantity)}
                </td>
                <td className="px-4 py-3 text-[#0F1115]/70">
                  {formatMoney(row.pricePerUnit)}/{row.unit}
                </td>
                <td className="px-4 py-3 font-semibold text-[#0F1115]">
                  {formatMoney(row.total)}
                  {!row.priceBookConfirmed && <span className="ml-1 font-normal text-[#0F1115]/50">(estimated)</span>}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <p className="border-t border-black/5 px-4 py-3 text-xs text-[#0F1115]/50">
        Prices marked (estimated) are generated by our live pricing engine but are not yet confirmed against a signed
        partner price sheet for that metro.
      </p>
    </div>
  );
}
