import type { GuideContent } from '../types';

export const cost: GuideContent = {
  slug: 'cost',
  path: '/gravel-driveways/cost',
  navLabel: 'Cost',
  title: 'Gravel Driveway Cost Per Sq Ft & Ton | MyGravelGuy',
  description:
    'Gravel driveway cost per square foot and per ton, with a live delivered-price example for a 12x50 ft driveway in DFW and Long Island.',
  h1: 'How Much Does a Gravel Driveway Cost Per Square Foot and Per Ton?',
  directAnswer:
    'Gravel driveway installation typically runs $1 to $10 per square foot, or $500 to $3,500 for an average driveway, depending on material, depth, and site prep. Material-only costs run $1 to $3 per square foot before delivery. See the live delivered price table below for a 12 by 50 foot driveway in DFW and Long Island.',
  howWeKnow:
    "The delivered-price table below is generated live from MyGravelGuy's own pricing engine — the same one used at checkout — not a generic national estimate.",
  lastUpdated: '2026-09-28',
  faqs: [
    {
      question: 'Is material cost or delivery cost the bigger driver of price?',
      answer:
        'Both matter, but site prep and depth usually swing the total more than the raw material price — a deeper or larger driveway needs proportionally more material and more delivery loads.',
    },
    {
      question: 'Does a 12x50 driveway example match my driveway?',
      answer:
        'It is a common single-car driveway size used for comparison. Use our calculator to get an exact quantity and price estimate for your own dimensions.',
    },
    {
      question: 'Why is the DFW price marked "estimated"?',
      answer:
        "DFW delivered pricing is generated by our live pricing engine but is labeled estimated until our DFW partner yard's signed price sheet is finalized.",
    },
    {
      question: 'Does the price include delivery?',
      answer:
        'Yes. The prices shown are delivered prices — material plus delivery to your zone — not a material-only price you would need to add delivery to separately.',
    },
  ],
};
