import type { GuideContent } from '../types';

export const dallasFortWorth: GuideContent = {
  slug: 'dallas-fort-worth',
  path: '/gravel-driveways/dallas-fort-worth',
  navLabel: 'Dallas-Fort Worth Guide',
  title: 'DFW Gravel Driveways: Cost & Materials | MyGravelGuy',
  description:
    'Gravel driveways in Dallas-Fort Worth: clay soil, drainage, materials DFW yards stock, and live delivered pricing.',
  h1: 'Gravel Driveways in Dallas-Fort Worth: Materials, Cost, and Drainage',
  directAnswer:
    "North Texas's expansive clay soil makes drainage and a compacted base essential for a gravel driveway to last. DFW yards commonly stock flex base for the compacted base layer and number 57 crushed limestone as the top driving surface. See live delivered pricing below for your ZIP code, and order directly for next available delivery across the DFW metro.",
  howWeKnow:
    "MyGravelGuy's DFW delivered pricing below is generated from the same live pricing engine used at checkout; it's marked as estimated until our DFW partner yard's price sheet is finalized.",
  lastUpdated: '2026-09-28',
  faqs: [
    {
      question: 'What gravel do DFW yards typically stock for driveways?',
      answer:
        'DFW yards commonly stock flex base (crushed limestone road base) for the compacted layer and #57 crushed limestone as the top driving surface, both suited to North Texas clay soil.',
    },
    {
      question: 'Why does clay soil matter for a DFW driveway?',
      answer:
        "North Texas's expansive clay soil shrinks and swells with moisture, which can crack and shift a driveway's base if it isn't compacted deeply enough or given somewhere for water to drain.",
    },
    {
      question: 'How much does gravel delivery cost in DFW?',
      answer:
        'See the live delivered-price table on this page for a current DFW estimate — pricing is generated by our pricing engine and updates as our DFW price book is finalized.',
    },
    {
      question: 'Do you deliver gravel across the whole DFW metro?',
      answer:
        'MyGravelGuy delivers across DFW Core (Dallas and Tarrant counties), DFW North (Collin and Denton), and DFW Outer zones (Rockwall, Kaufman, Ellis and Johnson) — enter your ZIP on our DFW order page to confirm your zone.',
    },
  ],
};
