// Gravel Driveway Cost Index — DFW market price data.
//
// GENERATED by scripts/metro/build-cost-index.mjs from:
//   - docs/metro/research/data/dfw/slug-stats.json (per-slug yard/broker n/min/median/max)
//   - docs/metro/research/data/dfw/catalog-proposal-v2.json (name/category/unit)
//   - docs/metro/research/data/dfw/prices-final.csv (sample date range + seller counts)
// Do not hand-edit — re-run the script instead:
//   node scripts/metro/build-cost-index.mjs
//
// This is a MARKET price index sourced from a September 2026 survey of 27
// DFW-area sellers (17 physical yards/producers, 9 online
// brokers/marketplaces) — independent of MyGravelGuy's own (still-placeholder) price
// book. See docs/metro/research/dfw-pricing-v2.md for full methodology, exclusions and
// caveats (thin samples, excluded rows, unit-conversion notes) and
// docs/metro/research/cost-index.md for the refresh procedure.
//
// Generated: 2026-09-28

export interface CostIndexStat {
  /** Distinct sellers contributing to this figure */
  n: number;
  min: number;
  median: number;
  max: number;
}

export interface CostIndexRow {
  /** Matches the DFW catalog slug in src/metro/config/data/dfwCatalog.ts (same material) */
  slug: string;
  name: string;
  category: 'gravel' | 'sand' | 'mulch' | 'soil';
  /** Sell unit these prices are per-unit of */
  unit: 'ton' | 'yd';
  /** Physical DFW yard/producer counter price (material only — delivery is separate, if any) */
  yard: CostIndexStat | null;
  /** Online broker/marketplace price with delivery included in the quoted price */
  brokerDelivered: CostIndexStat | null;
  /** Per-row caveat surfaced from dfw-pricing-v2.md, if any */
  note: string | null;
}

export interface CostIndexMeta {
  /** ISO date this data module was last generated */
  generatedAt: string;
  sampleStartDate: string;
  sampleEndDate: string;
  totalSellers: number;
  totalYardSellers: number;
  totalBrokerSellers: number;
  /** Path to the build script that produced this file, for the "how to regenerate" note */
  regenerateCommand: string;
  /** Public URL of the downloadable CSV distribution of this same data */
  csvUrl: string;
}

export const costIndexMeta: CostIndexMeta = {
  generatedAt: "2026-09-28",
  sampleStartDate: "2026-09-27",
  sampleEndDate: "2026-09-28",
  totalSellers: 27,
  totalYardSellers: 17,
  totalBrokerSellers: 9,
  regenerateCommand: 'node scripts/metro/build-cost-index.mjs',
  csvUrl: "/data/gravel-driveway-cost-index-dfw-2026-q3.csv",
};

export const costIndexRows: CostIndexRow[] = [
  {
    slug: "pea-gravel",
    name: "Pea Gravel (3/8\")",
    category: "gravel",
    unit: "ton",
    yard: { n: 6, min: 50, median: 71.43, max: 110 },
    brokerDelivered: { n: 3, min: 99.61, median: 106.77, max: 132.4 },
    note: null,
  },
  {
    slug: "57-limestone",
    name: "#57 Crushed Limestone",
    category: "gravel",
    unit: "ton",
    yard: { n: 8, min: 39.29, median: 64.29, max: 95 },
    brokerDelivered: { n: 3, min: 75.08, median: 84.54, max: 135.34 },
    note: null,
  },
  {
    slug: "flex-base",
    name: "Flex Base / Road Base",
    category: "gravel",
    unit: "ton",
    yard: { n: 5, min: 24.99, median: 46.43, max: 90.71 },
    brokerDelivered: { n: 3, min: 44.82, median: 84.5, max: 127.29 },
    note: null,
  },
  {
    slug: "decomposed-granite",
    name: "Decomposed Granite",
    category: "gravel",
    unit: "ton",
    yard: { n: 8, min: 66.42, median: 100.72, max: 153.57 },
    brokerDelivered: { n: 3, min: 104.4, median: 121.92, max: 125.89 },
    note: "Wide yard-class spread includes at least one colored/\"black\" DG variant pooled with natural DG — treat the median as a rougher estimate than the seller count alone suggests.",
  },
  {
    slug: "rip-rap",
    name: "Rip Rap",
    category: "gravel",
    unit: "ton",
    yard: { n: 1, min: 67.86, median: 67.86, max: 67.86 },
    brokerDelivered: { n: 1, min: 78.43, median: 114.71, max: 150.99 },
    note: null,
  },
  {
    slug: "river-rock",
    name: "River Rock 1-3\"",
    category: "gravel",
    unit: "ton",
    yard: { n: 6, min: 49.29, median: 102.5, max: 375 },
    brokerDelivered: { n: 3, min: 61.46, median: 233.36, max: 346.96 },
    note: "Wide yard-class spread ($49–$375/ton) reflects real size-grade variance (native river rock vs. 3-5\" decorative blends), not a data error — treat the median as a blended average across grades.",
  },
  {
    slug: "mason-sand",
    name: "Mason Sand",
    category: "sand",
    unit: "ton",
    yard: { n: 8, min: 48.15, median: 57.41, max: 100 },
    brokerDelivered: { n: 3, min: 78.43, median: 86.2, max: 96.64 },
    note: null,
  },
  {
    slug: "bank-sand",
    name: "Bank Sand (fill)",
    category: "sand",
    unit: "ton",
    yard: null,
    brokerDelivered: { n: 1, min: 72.04, median: 72.04, max: 72.04 },
    note: "No DFW yard-class rows found in the current dataset; the yard figure is carried over from an earlier single-seller scrape and is the lowest-confidence number in this index.",
  },
  {
    slug: "concrete-sand",
    name: "Concrete Sand",
    category: "sand",
    unit: "ton",
    yard: { n: 4, min: 54.07, median: 59.26, max: 71.11 },
    brokerDelivered: { n: 2, min: 61.92, median: 69.28, max: 76.63 },
    note: "Broker-delivered sample is thin (2 sellers) and sits close to the yard median — this is the one slug where MGG's proposed delivered price does not clear the broker-delivered median at the current premium rate.",
  },
  {
    slug: "play-sand",
    name: "Play / Playground Sand",
    category: "sand",
    unit: "ton",
    yard: { n: 1, min: 71.85, median: 71.85, max: 71.85 },
    brokerDelivered: { n: 3, min: 78.43, median: 94.74, max: 108.5 },
    note: null,
  },
  {
    slug: "washed-sand",
    name: "Washed Sand",
    category: "sand",
    unit: "ton",
    yard: { n: 2, min: 5.56, median: 58.34, max: 111.11 },
    brokerDelivered: { n: 2, min: 61.92, median: 85.21, max: 108.5 },
    note: null,
  },
  {
    slug: "native-hardwood",
    name: "Double-Shred Native Hardwood",
    category: "mulch",
    unit: "yd",
    yard: { n: 10, min: 26, median: 41, max: 70 },
    brokerDelivered: { n: 3, min: 62.87, median: 94.1, max: 153.71 },
    note: null,
  },
  {
    slug: "black-dyed",
    name: "Black Dyed Mulch",
    category: "mulch",
    unit: "yd",
    yard: { n: 5, min: 43, median: 45, max: 70 },
    brokerDelivered: { n: 2, min: 62.87, median: 108.29, max: 153.71 },
    note: null,
  },
  {
    slug: "brown-dyed",
    name: "Brown Dyed Mulch",
    category: "mulch",
    unit: "yd",
    yard: { n: 2, min: 43, median: 48, max: 53 },
    brokerDelivered: null,
    note: "No broker-delivered sellers found for this material — broker column is not comparable, yard-class only.",
  },
  {
    slug: "dyed-red",
    name: "Red Dyed Mulch",
    category: "mulch",
    unit: "yd",
    yard: { n: 5, min: 38, median: 46, max: 53 },
    brokerDelivered: { n: 2, min: 62.87, median: 99.71, max: 136.55 },
    note: null,
  },
  {
    slug: "cedar",
    name: "Cedar Mulch",
    category: "mulch",
    unit: "yd",
    yard: { n: 3, min: 55, median: 59, max: 65 },
    brokerDelivered: { n: 1, min: 78.3, median: 78.3, max: 78.3 },
    note: null,
  },
  {
    slug: "pine-bark",
    name: "Pine Bark Mulch",
    category: "mulch",
    unit: "yd",
    yard: { n: 3, min: 50, median: 55, max: 63 },
    brokerDelivered: { n: 1, min: 78.3, median: 78.3, max: 78.3 },
    note: null,
  },
  {
    slug: "playground-mulch",
    name: "Playground Mulch",
    category: "mulch",
    unit: "yd",
    yard: { n: 2, min: 17.99, median: 44.99, max: 52 },
    brokerDelivered: { n: 2, min: 78.3, median: 139.9, max: 201.49 },
    note: null,
  },
  {
    slug: "sandy-loam",
    name: "Sandy Loam Topsoil",
    category: "soil",
    unit: "yd",
    yard: { n: 10, min: 10, median: 45, max: 65 },
    brokerDelivered: { n: 4, min: 17, median: 82.69, max: 105.88 },
    note: null,
  },
  {
    slug: "garden-mix",
    name: "Garden / Raised-Bed Mix",
    category: "soil",
    unit: "yd",
    yard: { n: 9, min: 40.99, median: 62.5, max: 176 },
    brokerDelivered: { n: 2, min: 104.22, median: 105.12, max: 113.55 },
    note: null,
  },
  {
    slug: "compost",
    name: "Compost",
    category: "soil",
    unit: "yd",
    yard: { n: 6, min: 40, median: 52.5, max: 70 },
    brokerDelivered: { n: 1, min: 67.87, median: 73.4, max: 78.92 },
    note: null,
  },
  {
    slug: "select-fill",
    name: "Select Fill Dirt",
    category: "soil",
    unit: "yd",
    yard: { n: 6, min: 3.5, median: 27.97, max: 46.67 },
    brokerDelivered: { n: 4, min: 10, median: 54.91, max: 63.44 },
    note: null,
  },
];
