// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhlubwjelejctljcxwwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlobHVid2plbGVqY3RsamN4d3d5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0Mzk4MTcsImV4cCI6MjA2MTAxNTgxN30.y1TxzifGVpdHutSgZsQBVHAq9I_MjGhz0NhcFOO65ko";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);